name: roberta-large
class_name: RobertaForMaskedLM
tokenizer_class: RobertaTokenizerFast
tokenizer_name: roberta-large
inner_params:
- roberta.encoder.layer.22.intermediate.dense.weight
- roberta.encoder.layer.22.output.dense.weight