name: roberta-base
class_name: RobertaForMaskedLM
tokenizer_class: RobertaTokenizerFast
tokenizer_name: roberta-base
inner_params:
- roberta.encoder.layer.0.intermediate.dense.weight
- roberta.encoder.layer.0.output.dense.weight